version: "0"
services:
  servico:
    build:
      context: ./servico-service/
    depends_on:
      - discovery
  simulacao:
    build:
      context: ./simulacao-service/
    depends_on:
      - discovery
  discovery:
    build:
      context: ./discovery-service/
    ports:
      - "8761:8761"
  gateway:
    build:
      context: ./gateway/
    ports:
      - "8080:8080"
