server:
    port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: simulacao
                  uri: lb://simulacao
                  predicates:
                  - Path=/simulacao/**
                - id: servico
                  uri: lb://servico
                  predicates:
                    - Path=/servico/**
